# Generated by Django 5.2 on 2025-12-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_application_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='category',
            field=models.CharField(blank=True, choices=[('ORPHAN', 'Orphan or child without parental care'), ('LARGE_FAMILY', 'Large family with awards or many children'), ('SOCIAL_VULNERABLE', 'Socially vulnerable group'), ('GOVERNMENT_EMPLOYEE', 'Government employee'), ('BUDGET_WORKER', 'Budget organization worker'), ('MILITARY', 'Military personnel'), ('ASTRONAUT', 'Astronaut or candidate'), ('ELECTED_OFFICIAL', 'Elected official'), ('EMERGENCY_HOUSING', 'Citizen with emergency housing')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='large_family_awards',
            field=models.CharField(blank=True, choices=[('NO_AWARD', 'Нет наград'), ('ALTYN_ALQA', 'Altyn alqa'), ('KUMIS_ALQA', 'Kumis alqa'), ('MOTHER_HEROINE', 'Mother heroine'), ('MATERNAL_GLORY_I', 'Maternal glory I'), ('MATERNAL_GLORY_II', 'Maternal glory II')], max_length=50, null=True),
        ),
    ]
